# Alan Murphy - 12/12/20


-- Script generated by USE 4.2.0

gits a pain in the bollix
!v1.tel := '123456'
!new Veterinarian('v2')
!v2.name := 'Susy'
!v2.visit_cost := 20
!v2.tel := '123457'
!new PetOwner('me')
!me.name := 'Tom Smith'
!me.bank_balance := 1000
!new Cat('molly')
!molly.name := 'Molly'
!molly.age := 7
!molly.type := 'Siamese'
!molly.visits_to_vet := 10
!molly.hunts := true
!new Cat('puss')
!puss.name := 'Puss'
!puss.age := 5
!puss.type := 'Tabby'
!puss.visits_to_vet := 3
!molly.hunts := false
!new Dog('rex')
!rex.name := 'Rex'
!rex.age := 10
!rex.visits_to_vet := 15
!rex.bark := 'loud'
!rex.energetic := true
!insert (me,molly) into Owns
!insert (me,puss) into Owns
!insert (me,rex) into Owns
!me.setVetFor(v1, molly)
!me.setVetFor(v2, puss)
!me.setVetFor(v2, rex)


